### ISSUE TITLE
[BUG] Domino 12.0.2 backup & directory junction - data directory split across multiple disks

### ISSUE THREAD

**Issue by tjirka-dcit** [HCL-TECH-SOFTWARE/domino-backup#20] opened 2024-03-19 15:25 UTC
**HCL Product Version**
Domino 12.0.2 FP3

We have directory junction on our Domino server installed on Windows Server in data directory.
d:\notes-data\some_directory
->
g:\notes-data-linked\some_directory

We are getting errors for every db in that directory on another disk:
Backup: Cannot backup database in Backup VSS mode - Database volume path [some_directory\db_name.nsf] is not in data directory volume path

**Comment by tjirka-dcit** [comment] 2024-03-19 17:13
Creating folder link using Domino Administrator File Browser and using that instead of NTFS directory junction did not helped, Domino Backup writes same errors.


And I probably should have admit that we are running that Domino server on Windows Server 2016, which is probably not supported.
We were running Domino server on supported version of Windows Server but somehow during upgrades to newer and newer version it has phased out. And I have noticed it only recently (I think that Windows Server 2016 stopped to be supported with some Fix Pack od Domino version 12 - it didn't occur to me that this was possible since Microsoft still supports that version of Windows Server), and from that time I still did not get to upgrading Windows Server to supported version.

**Comment by Daniel-Nashed** [comment] 2024-03-19 19:10
As documented you can only have one volume to store NSF databases in VSS Writer mode.
For a flexible integration supporting many different backup providers and restore scenarios is very difficult to implement support for multiple volumes. This was a design decision early on in the project.

Therefore the backup application checks if databases are on the same volume.
This check is implemented on purpose to ensure you are not having any backup that is not complete and works as intended. 

There are currently no plans to extent the functionality. 
You might want to add an enhancement request/idea --> https://domino-ideas.hcltechsw.com/ideas

Note: We just had a case where an admin had archive data on the same server and for them excluding those database from download was helpful for them.

I am removing the bug tag, but I am keeping it open waiting for your replies.

**Comment by tjirka-dcit** [comment] 2024-03-19 21:46
Thank you for prompt reply. It is now clear to me, so the thing is that only one disk volume to store NSF databases is supported for VSS mode.

Can be may be that error message be modified to make it a lit bit more clear, may be something like this:
Backup: Cannot backup database in Backup VSS mode - Database volume path [some_directory\db_name.nsf] is not in data directory volume path - VSS Writer mode supports only one volume to store NSF databases

Do I think correctly that there is other option besides VSS Writer mode? Something like disabling backupvss task and Veeam calling some scripts when doing backup.

I would like to add that I have proper Domino Backup configuration still on TODO list (many other things to do). But because I have found that vss integration can make backups more consistent seemingly without much effort in Domino 12.0.2, I have tried it now without postponing it. Before that I was just calling script with "drop all" and "dbcache flush" (and having transaction log enabled), and to be more precise I am still calling it, thinking that is not necessary now but harmless (and I will probably remove the "c:\Program Files\VMware\VMware Tools\backupScripts.d\domino-flush.cmd" script at some point, if the new vss backup works without problems for a while).


I will probably try first to solve it by moving those dbs back to data directory, is is on different disk because I have had this problem with one of dbs in that directory:
[0A78:0007-184C] 14.06.2019 21:33:44  Error compacting some_directory\some_db.nsf, -c -i -n -v some_directory\some_db.nsf: The requested operation could not be completed due to a file system limitation

According to IBM support it was not Domino problem: "The issue with this error is purely from OS and not Domino, you need to contact Microsoft for further help ..."

I have managed to solve it by moving that directory to newly created disk. It was some older Windows Server version before, so may be it will work now. And if not I will try to create new big (virtual) and copy whole data directory to it while Domino shutdown. I have test environment at hand using Veeam SureBackup with storage snapshot integration and on disk array there is currently plenty of space, so it should not be problem to test.

**Comment by Daniel-Nashed** [comment] 2024-03-19 22:09
You should really use VSS Backup which is the most native integration on the Windows side.
In Domino 12.0.1 there was already a Windows Veeam integration with freeze scripts. 
We highly recommend using the VSS approach, which avoids creating delta files during snapshot backup and make the databases always consistent.

If this is a special case and error condition, I would try to resolve the issue in move the databases back.
"IBM Support" sounds like an old problem. 
I would also recommend moving from compact to DBMT which is the more modern method of compact.

Also please be aware `-i` is a last resort compact option, which should only used in very special cases.
Enabling compression via `-n -v` is a one time operation which needs the compact task. 
But you could run it in two steps:

```
load compact -n -v
load dbmt
```

Flushing databases before a standard Veeam backup is not a valid solution. Databases might still be open afterwards and you have no native Domino Restore integration. Native Veeam restore is a different admin experience and involves a Veeam admin operation.

**Comment by tjirka-dcit** [comment] 2024-03-25 22:29
Btw I have managed to move databases back to data directory, and those errors are gone.

**Comment by Daniel-Nashed** [comment] 2024-03-26 08:16
Thanks for your feedback. So I can close the Issue.  Great that it is resolved for you!

**Closed by Daniel-Nashed** 2024-03-26 08:16 UTC
Labels: enhancement
