### ISSUE TITLE
Azure snapshot backup a file-consistent backup is created and some databases are corrupted.

### ISSUE THREAD

**Issue by JMMM77** [HCL-TECH-SOFTWARE/domino-backup#9] opened 2023-06-14 11:12 UTC
**HCL Product Version**
HCL Domino 12.0.2FP1

**Describe the bug**
When doing an Azure snapshot backup a file-consistent backup is created and some databases are corrupted.
https://learn.microsoft.com/en-us/azure/backup/backup-azure-vms-introduction#snapshot-consistency

**Error Message**
If an error message is displayed, include details here. Quickly identifying the code causing the error will help to more quickly resolve it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a Windows Server 2019 Azure Virtual Machine
2. Run an HCL Domino server on HCL Domino 12.0.2FP1
3. While the Domino Server is running, Run a Azure Backup by going to the Backup Instance of the VM in the Azure Portal and clicking Backup Now
4. You can see that backupvss is doing something in the logs but the Azure Backup is still a file-consistent backup instead of a application consistent

**Expected behaviour**
An Application Consistent Backup is created when performing an Azure Backup with the Domino Backupvss task running and the databases are not corrupted. 

**Screenshots**
Crash Consistent Backups are taken when the server was offline.
Application Consistent Backups were taken when Domino was stopped or running without the backupvss task.
File Consistent Backups were taken when Domino is running
https://learn.microsoft.com/en-us/azure/backup/backup-azure-vms-introduction#snapshot-consistency
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/91952323/08096206-0aa0-4839-81a0-916116234bea)

**Domino Backup Database Configuration**
Main Tab:
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/91952323/06f718b2-5d43-4d36-b78d-1e206e36b316)
Backup Tab:
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/91952323/48502528-c58a-40f6-82da-5fca8828fa26)
The rest of the tabs are default.

**Desktop (please complete the following information):**
 - OS: Windows Server 2019

**Additional context**
I was asked by HCL Software Customer Support to open a GitHub Issue after I raised a support case with HCL "CS0394460" regarding this issue.

I have tried the following using the backupvss task introduced in Domino 12.0.2:
- Take a snapshot without the task running but the Domino server was running (caused an application consistent backup but log.nsf was corrupted so it was not a reliable backup)
- Take a snapshot while the task was running and the Domino Server was running (caused a file consistent backup but a delta file was created for log.nsf and ddm.nsf based on the backup configuration in dominobackup.nsf)
- Take a snapshot with "USEVSSCOPYBACKUP"="TRUE" set in the Windows registry and excluded log.nsf and ddm.nsf from the configuration file (caused a file consistent backup but no delta files were created)

I could not see anything in Azure, event viewer, ddm, or log.nsf that showed that the backup had any errors.

I am expecting that the backups should be application consistent as this means that all vss snapshots succeeded. https://learn.microsoft.com/en-us/azure/backup/backup-azure-vms-introduction#snapshot-consistency

 Where is the VSS_VOLSNAP_ATTR_AUTORECOVER set? Is it on the virtual machine or on the application that creates the snapshot? Also, How would I be able to verify if this option is set?

**Comment by JMMM77** [comment] 2023-06-14 11:13
If the above is not possible, would you be able to tell me what the best practice is for creating a backup of the Domino Data directory on Azure Virtual Machines, preferably using snapshot backups and storing the backups in Azure, please?

**Comment by Daniel-Nashed** [comment] 2023-06-14 22:17
First of all the platform needs to support application consistent snapshots. Sadly we had no chance to fully test it on our own. 
At the time I looked at it The platform wasn't able to handle application consistent snapshots.

The VSS back end would be responsible to call the right VSS back-ends to have Domino backupvss be trigged in the right way.

Can you enable debugging via load backupvss -d and keep the console open?
The console will write the VSS events from the VSS back-end to the console. Those logs only show on the console, because the code called in those back-ends are not Domino thread initialized (because they are back-end VSS callbacks).

I need the VSS events to see what the Azure platform uses in that way. You UI indicates you had some backup invocation, which might have triggered application aware backup. others didn't for sure.

The logs would be the first step. 
Domino backup really just implements the VSS back-end we can't try all environments on our own, know know how to configure them on the platform side. Like Azure. You are the first one to try it.

We for sure want to understand this scenario, want to get it work and share it with others later!

**Comment by Daniel-Nashed** [comment] 2023-06-14 22:20
If an application does not perform application aware snapshots, backupvss should automatically write the delta files and leverage your configuration. In this type of configuration beside the snapshot backup your file backup would be used. Only the snapshot and the delta would work together on a restore and you have to take care of backing up the delta files.

In your case you are excluding log.nsf and ddm.nsf. This will cause the databases to not write their delta logs, even their full backup is in the snapshot.

I hope this clarifies how it works?

**Comment by JMMM77** [comment] 2023-06-15 10:55
Hi Daniel,

Ill give running `load backupvss -d` a go and come back to you when I have the results.

When the log.nsf and ddm.nsf were not in the list I could see the delta files being created, however, how would I be able to restore the snapshot and delta files to restore those 2 files and potentially any other files affected?

I am still a bit confused on the Application Aware snapshots, how do I know if the application, I guess in this case Azure, is application-aware or even has the auto-recovery option enabled (VSS_VOLSNAP_ATTR_AUTORECOVER).

https://help.hcltechsw.com/domino/12.0.2/admin/admn_vsssnapshots.html

**Comment by Daniel-Nashed** [comment] 2023-06-18 10:46
what is confusing here?
the VSS auto recovery option is part of the VSS API. 
the application needs to support it. when you include the database and the .delta files are not created, databases in use, are inconsistent.

the application aware snapshot offers to backupvss to mount the snapshot after the snapshot to add delta data.
so databases are consistent in the snapshot.

if a backup application does not support auto recovery snapshots, Domino backup has to create delta files.
And the restore operation needs to have access to those delta files during restore.

The restore integration needs to have access to the delta files.
This is working as intended and there is no other way.

When I took a quick look into Azure I did not see any auto recovery snapshots. That was quite a surprise, because VSS is a core Windows functionality from Microsoft.

Probably in the logs we will see that no post snapshot event occurs and Domino backup has to create the delta files as described.

You can't just exclude the files to not get delta files, to work-around that.

One of the logs from the Azure side looked like there is a auto recovery snapshot in some of the backups.
Can you raise this at Microsoft? I can't help you on the Azure side. 

-- Daniel

**Comment by Daniel-Nashed** [comment] 2023-07-13 16:14
Thanks for the logs. The output of the VSS part are only written via printf, because no Domino code can be used. 
We could potentially proxy those error messages to the Domino side of backupvss and print it.
But it is just intended for troubleshooting and not used in normal cases.
The -d added the following type of log output:

```
DominoVSSWriter::OnPostSnapshot Post backup changes applied after 1 seconds.
```

And we are missing the auto recovery part! The VSS back-end does not provide the snapshot to mount it for writing. 
So we cannot create an auto recovery snapshot.

You have to check with the provider to see if and how this can be enabled.

sYour screenshot contains different data than the log you send. 

Side note: Can you please only send text instead of graphics in future. It would be much easier to handle. 

In the screenshot case there is a delta file created and it should be also written. else you should get an error message.
In the other test there was no delta file, which was created. No database needed one.

I noticed another error in your log:

```
BackupVSSCompletedTimeUpdate: Error opening backup result log document: Entry not found in index
```

This error occurs when the backup complete time is happening earlier than expected. Normal backup snapshot applications take some time to write the snapshot data to a back-end location. In this case nothing is copied and they immediately return.

We had this with another backup provider and this issue is just failing the final update of the backup complete time into the log.
There is a SPR, which is fixed in V14 and also in 12.0.2 FP2 coming up this month.

I would need more information to understand why your one delta file was not written. in case of an error, you should see an error message. 

For the auto complete snapshot you really need to speak to your vendor. I can confirm we are not receiving the volume information in the OnPostSnapshot event.

If you want to pass details to them, here is a link:

https://learn.microsoft.com/en-us/windows/win32/api/vswriter/nf-vswriter-cvsswriter-onpostsnapshot

See the section mentioning **VSS_VOLSNAP_ATTR_AUTORECOVER**

I hope this helps for the next steps?

Daniel

**Comment by JMMM77** [comment] 2023-07-14 11:53
Hi Daniel,

Thank you for your reply.

I have sent the Cloud Providers the details from your previous reply and they have escalated it to Microsoft.

Regarding the `BackupVSSCompletedTimeUpdate: Error opening backup result log document: Entry not found in index` error, is it correct to assume that this will be fixed in HCL Domino Server 12.0.2 FP2?

Also, for these tests, I changed the Log On As for the HCL Domino Server Service to be Local System Account as the DominoSvc User Account we created to run the HCL Domino Service was failing to start the Domino Backup Writer, see logs below:

Im not sure whether this should be in a separate issue or not?
```
load backupvss -d

[262C:0002-2630] 14/07/2023 09:35:35   BackupVSS: Domino Backup VSS plug-in started
[262C:0004-2640] 14/07/2023 09:35:35   BackupVSS: CVssWriter::Initialize failed
[262C:0004-2640] 14/07/2023 09:35:35   BackupVSS: Domino Backup VSS plugin
BackupVSS: DominoVSSWriter::DominoVSSWriter called
BackupVSS: DominoVSSWriter::~DominoVSSWriter called
BackupVSS: DominoVSSWriter::Uninitialize called
[262C:0002-2630] 14/07/2023 09:35:38   BackupVSS: Domino Backup VSS plug-in shutdown
```

I suspected it was due to permissions as I could see in the Application Event Log: 

```
Volume Shadow Copy Service error: The process that hosts the writer with name Domino Backup Writer and ID {dee12323-b0ce-4f3d-8d3a-68062f1c53cc} does not run under a user with sufficient access rights. Consider running this process under a local account which is either Local System, Administrator, Network Service, or Local Service. 

Operation:
   Initializing Writer

Context:
   Writer Class Id: {dee12323-b0ce-4f3d-8d3a-68062f1c53cc}
   Writer Name: Domino Backup Writer
```
How could I get the DominoSvc local user account to be able to work with the backupvss task?

I have tried adding the local user account to the Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\VSS\VssAccessControl as a DWORD and gave it permissions to the Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\VSS\Diag folder. 

This allowed the Domino Backup Writer to successfully run but when running the Azure Backups no logs were being generated and in the event viewer I could see the below Error:

```
Volume Shadow Copy Service error: Unexpected error querying for the IVssWriterCallback interface.  hr = 0x80070005, Access is denied.
. This is often caused by incorrect security settings in either the writer or requestor process. 

Operation:
   Gathering Writer Data

Context:
   Writer Class Id: {dee12323-b0ce-4f3d-8d3a-68062f1c53cc}
   Writer Name: Domino Backup Writer
   Writer Instance ID: {4bc61f16-390b-4832-b910-370681d15831}
```
I have tried the below but none have succeded:
 - Added the System and Network Service the registry
 - Added the DominoSvc account to the Backup Operators group
 - Added the DominoSvc account to the COM Security for "My Computer" in Component Services
 - Added the DominoSvc account to the Volume Shadow Copy Service, component service with local launch and activate permissions

Please let me know if there are any issues.

**Comment by Daniel-Nashed** [comment] 2023-07-15 06:08
Ohh just checked. The issue with the update of the backup finished time  did not make it into FP2. It's planned for 12.0.2 FP3 and is addressed in Domino V14 EA2 (SPR #DNADCSBHWZ).

I don't think this is a permission problem. you really need to work with Microsoft to get this resolved. The VSS writer does not have any information about the snapshot. the event is not called. The writer can't do anything about it. It's a matter how the VSS snapshot is created.

**Comment by JMMM77** [comment] 2023-07-18 12:41
Hi Daniel,

I am still working with Microsoft support to look into this issue, would you like me to keep you up to date with what I am communicating with Microsoft?

Also, I enabled vss debugging unsure if that is helpful but I also noticed that after running vssadmin list writers after the backup was complete I saw that the WMI Writer had timed out but the Domino Backup Writer did not error, please see files attached.

https://learn.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/enable-debug-tracing-features-vss

[20230718 Test Azure Backup With load backupvss -d.txt](https://github.com/HCL-TECH-SOFTWARE/domino-backup/files/12080504/20230718.Test.Azure.Backup.With.load.backupvss.-d.txt)
[20230718 vss snapshot trace.txt](https://github.com/HCL-TECH-SOFTWARE/domino-backup/files/12080505/20230718.vss.snapshot.trace.txt)
[20230718 vssadmin list writers before and after.txt](https://github.com/HCL-TECH-SOFTWARE/domino-backup/files/12080506/20230718.vssadmin.list.writers.before.and.after.txt)

**Comment by Daniel-Nashed** [comment] 2023-07-18 12:57
Yes please keep me updated on feedback from Microsoft. But I don't think we look into traces on our own until Microsoft replies with something that needs us to research. 

We need them to support auto recovery snapshots. And it does not look like they do at least in this environment.

I tried it with Hyper-V earlier and I also did not get auto recovery snapshots work.
The interesting part here is that VSS, Hyper-V and Azure are Microsoft applications, which should fully support each other... 

-- Daniel

**Comment by JMMM77** [comment] 2023-07-18 13:06
Hi Daniel,

I have attached the response from Microsoft, also are you aware of when the 12.0.2FP3 is planning on being released?

[Reply from microsoft.pdf](https://github.com/HCL-TECH-SOFTWARE/domino-backup/files/12080736/Reply.from.microsoft.pdf)

**Comment by Daniel-Nashed** [comment] 2023-07-18 18:29
Thanks for the info.

It does not make sense to discuss with them the details of the Domino feature.
The Domino VSS writer will use the snapshot when it is presented via the PostSnapshot event.
The caller of the VSS snapshot/backup is responsible for using the right options to make it a consistent snapshot.

This is usually the case for most applications like Veeam and others. But it looks like neither Azure nor Hyper-V use this option.

Even the very simple Windows server backup application supports application aware snapshots.
But this isn't the default. The calling applications is responsible for setting the right parameters.

The info from Microsoft is a first answer, but this isn't really fully helpful.
It's their responsibility to use the right options when creating the snapshot.

The dominovss task just consumes the calls from the VSS back-end. 
And it dumps what it receives.

**Comment by JMMM77** [comment] 2023-07-20 08:40
Hi Daniel,

I think I created a misunderstanding with them regarding the type of file extension the database is as it is a NSF rather than NFS, I will wait for their reply.

[20230720 Reply from Microsoft.pdf](https://github.com/HCL-TECH-SOFTWARE/domino-backup/files/12103942/20230720.Reply.from.Microsoft.pdf)

**Comment by Daniel-Nashed** [comment] 2023-07-20 15:55
The snapshot is not generated in the right way. and it looks like they don't know their own VSS technology. I added all the details about it from API perspective. I don't say VSS technology or the API is easy.. But it's pretty interesting that you as a customer have to raise issues with different teams.  I hope you get this resolved. Keep us posted, but I can't do more than describing how it works and how you can look at the logs from Domino side.

The VSS API is implemented as a C++ class with call-backs. You register for certain events and you are called.
This is all controlled by the VSS back-end.

A backup provider has to use the VSS API in the right way to get the VSS to perform the right operations, which are all handled by the VSS back-end.

-- Daniel

**Comment by Daniel-Nashed** [comment] 2023-07-21 10:10
I am changing this from but to help wanted. This does not look like working as intended on the Domino side. We still want to help you and we are in discussion how we can provide information to help backup vendors to have their software to use the right snapshot options. 

Please keep us updated what you get back from the vendor.

**Comment by Daniel-Nashed** [comment] 2023-07-25 16:47
The beauty of the VSS application consistent snapshots (auto recovery) is that Domino can merge it's deltas directly into the snapshot and close the databases which are still in backup mode during the snapshot.

File consistent backup is not an option for Domino if the database is open. You have to use the backup API and this is what Domino backup does in the back-end for you when VSS triggers the snapshot.

1. VSS triggers the snapshot
2. backupvss gets the events and invokes the backup task which brings all databases into backup mode
3. once done the event continues operations and VSS generates the snaphot
4. with auto recovery snapshots VSS presents the snapshot to the VSS writers (this is your missing step)
5. Domino stops the backup mode for all databases and gets the delta data
6. Domino will then merge the deltas into the databases and also close databases even no delta occurred
7. Once done VSS makes the final snapshot available to the calling backup initiator 

In your case no Auto recovery snapshot is taken and the databases need recovery on restore.
The delta files that occur can be backed up to another place and are used to recover databases later.
You have to apply the delta files and recover databases! There is no other way to make databases consistent.
Everything else isn't supported. Don't let them tell you it is a safe file consistent backup. If it would, we would not need any Domino backup ..

Restoring with delta files and a snapshot is a lot more complicated to configure. Once configured Domino restore would take care of the steps.

You would need Domino restore to look into the snapshots and get a snapshot mounted. and also needs a way to access the matching delta files.

That's the main reasons why we really want auto recovery snapshots. It dramatically simplifies backup and restore operations.
In addition the resulting NSF files in the snapshot are recoverable without Domino!
This is specially important for disaster recovery scenarios.

We are thinking about providing a C++ example how to create an auto recovery snapshot. 
HCL has implemented a basic backup module for automation testing purposed and we might be able to make this available for other to look into to understand which components are missing to make a VSS snapshot auto recovery enabled.

**Comment by JMMM77** [comment] 2023-07-26 14:51
Hi Daniel,

Thanks for confirming I have passed the details along, I have started following you on LinkedIn as I was hoping that I would be able to include you in the email trail between me and Microsoft so that you are kept up to date.

**Comment by JMMM77** [comment] 2023-07-28 09:15
Hi Daniel,

I would like to apologise, I have spoken with one of my Managers and he has asked me to park it as I have spent too much time working on this issue. 10 days in total for looking into a backup solution, including the 4 days spent looking at this backup solution using backupvss.

Due to this, I am unable to complete the steps that you have asked me to complete. However, I have asked Microsoft if they would be able to further with you or the HCL Domino Backup team to investigate this further.

Sorry for not being able to assist further.

**Comment by Daniel-Nashed** [comment] 2023-07-28 09:36
Sorry to hear you spend that much time. But I must say this isn't a Domino problem.
There is also nothing to work with HCL directly on this. This is basic Microsoft VSS functionality.
The Azure team has to speak with the right team at Microsoft.

VSS is a standard Windows functionality and if an own Microsoft service can't provide Auto Recovery snapshots, there is nothing we can do to help with this type of backup.

You can still use a snapshot with delta files. But this is a bit more complex to implement and we really want VSS with auto recovery snapshots to also allow longer term consistent backup.

Other vendors like Veeam support Auto Recovery snapshots automatically. And even the simple Windows backup application does support it.

I would really like to see that Microsoft supports it in Azure and also with Hyper-V where I also didn't find a way to use it earlier.
This might be the underlying reason why Azure can't support it.

With VSS Auto Recovery, the backup part of Domino could be configured in like half an hour.
Only the optional but good to have directly Notes database driven restore needs some integration.

I am sorry that I can't help in this situation.  I changed the topic of this to not show up as a bug. it isn't a bug on the Domino side from what we can tell. 

Can I close the issue if you can't work on it any more?

Thanks

Daniel

**Closed** 2023-11-15 13:42 UTC
Labels: help wanted
