### ISSUE TITLE
Restore not working with Veeam integrated domino.

### ISSUE THREAD

**Issue by Prabhatkumarsandvik** [HCL-TECH-SOFTWARE/domino-backup#10] opened 2023-06-15 17:01 UTC
**HCL Product Version**
Which version of the relevant HCL product is in us:-Domino 12.0.2FP1

**Describe the bug**
We are in the process of migrating the backup solution to veeam. We are able to configure backup and it's working fine.

While restoring the database we are getting an admin account not found error. But required access has been granted to the AD account on veeam server.

Raised the case with Veeam and hcl but seems it's an issue with the integration script. Does anyone have any idea about this backup? 

**Error Message**
If an error message is displayed, include details here. Quickly identifying the code causing the error will help to more quickly resolve it.
NO ADMIN ACCOUNT FOUND

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Additional context**

**Comment by Daniel-Nashed** [comment] 2023-06-15 17:21
Hi,

thanks for raising this issue. Your issue does not have sufficient information to help you.
This does not sound like a defect, but a configuration issue.

When using the Veeam integration. please make sure you are using the native VSS Writer support in Domino 12.0.2 as described for the Domino 12.0.2 integration. This provides you with full snapshnot support in Windows using the VSS Writer.

Only for restore you will need an integration. For backup all steps are handled by the Backup writer.

Can you please first make sure you have the new modern integration. You should not run the earlier integration for Windows any more, now that there is a native VSS Writer integration.

For this integration we wrote a simplified instruction just covering the exact steps for this type of configuration.

There are a couple of steps you have to perform to integrate the restore script.

Can you please verify first you have performed all the steps listed here -> https://opensource.hcltechsw.com/domino-backup/backup-providers/veeam/install_vss_writer/

Then please make sure where you see the error message.

The restore script invokes ssh, which then invokes a power shell script on the Veeam server.
Since Domino 12.0.2 there is end to end logging, which provides the log document directly in restore document.

If you can't share the logs here, please make sure escalates your ticket. Since you don't provide your customer name here, I don't know if you are the case I am right now involved in, where I am waiting for logs and details.

**Comment by Prabhatkumarsandvik** [comment] 2023-07-05 16:19
Here is the output.

get-vbrcredentials

Name                           Description
----                           -----------
seint3615\notes                seint3615\notes

Hi HCL Team,

After changing the username in hierarchical format in config file ("notes" to "seint3615\notes"), Error "no administrator account found" has been resolved. However now we are facing the below error. Can you please check ?

2023-06-30 13:07:44 Mounting backup restore point: e1c431bc-f050-46d2-895b-a54a7a6b518a Backup Time Local: 2023-05-05 13:19:31 Backup Time UTC: 2023-05-05 11:19:31
Publish-VBRBackupContent : Failed to publish backup content. The user name or password is incorrect.
Failed to connect to share '\\164.4.32.104\ADMIN$'
.
At C:\dominobackup\DominoRestore.ps1:251 char:23
+ ... reSession = Publish-VBRBackupContent -RestorePoint $RestorePoint -Tar ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidResult: (:) [Publish-VBRBackupContent], CAppException
+ FullyQualifiedErrorId : PublishVBRBackupContentErrorId,Veeam.Backup.PowerShell.Cmdlets.PublishVBRBackupContent


Thanks & Reg:
Prabhat

**Comment by Prabhatkumarsandvik** [comment] 2023-07-05 16:22
There is no problem with the Notes account and password on the Veeam server. It is working at OS level. However when we are trying to restore the database through script it is showing username & password issue.

Looks like the process is stuck on the code below. Can you tell us from where it is getting the password for the “seint3615\notes”  account. Even we are not using “seint3615\notes” password to connect to Veeam server. It is using only SSL connectivity.

Is local window “notes” account also required on Domino server (164.4.32.104) ?

  {
    $RestoreSession = Publish-VBRBackupContent -RestorePoint $RestorePoint -TargetServerName $RestoreTarget -TargetServerCredentials $TargetAdminCreds -Reason "Domino Restore operation"
  }
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/136735294/c144df83-a8f0-4cb1-b2a4-698f14a9a852)


 



Thanks & Reg:

Prabhat[](url)

**Comment by Daniel-Nashed** [comment] 2023-07-21 10:08
I changed the label from bug to help wanted. this is not a bug. this is a configuration issue from what it looks like.
We keep it open. But you really need someone to help you on the Veeam side.

**Comment by Prabhatkumarsandvik** [comment] 2023-07-24 16:45
Hello Daniel,

Thank you for your update!

We are now able to backup our Domino database via Veeam and restoration is also working fine. Requesting you to please share documentation regarding how the Domino directory link works with veeam backup.

Also please suggest how archival logs backup logs via veeam.
Thanks, Prabhat

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Daniel-Nashed** [comment] 2023-07-25 05:41
Good to hear it now works for you. 
Can you describe in more detail what you are trying to do with directory links?
All the NSF data must be a on single volume. Directory links are only supported on the same disk/volume. 
Domino backup is explicitly checking if all the data is on the same device and returns errors for databases outside the same volume. 
You can split 

- **NSF** -> This is what needs online backup
- **NIFSNSF/FT**  does not need a backup
- **DAOS**  can be backed up separately without an online backup)
- **TRANSLOG** needs separate backup

But you can't split NSF when you use snapshot Domino backup.
And there are no plans currently to change this.

The background is the complexity this would add on backup and restore.

---

Archive style Translog is a separate functionality in Domino backup/restore and cannot be combined directly with a snapshot backup.

Transaction logs are written step by step and need to be copied step by step. this doesn't match up with snapshot backup.
You can still configure translog backup when using Veeam using a file integration. For example you can store those translog extends via file copy operations or other integrations for S3. 

Snapshots would not really work for translog data, because you would need to restore multiple snapshots.
Still it can be combined. 

But please keep in mind that this is a much more complex setup than just a snapshot backup.

I don't know what your use case for archive style translog is.

Archive style translog is usually a good way to reduce the backup time and volume by only backing up the deltas during the week. With snapshot backup you have a completely different approach for backup and archive style backup is not required for snapshot backup from storage point of view.

Still you might also want to use it for point in time recovery -- which is the second aspect of archive translog.
To keep your configuration simple, you could use linear transaction logging (circular translog just with more space) and can point in time restore for some days at least.

Snapshot backups are not really a good match for snapshot backup. You would need to mount too many volumes for the restore case. 

I hope this helps

Daniel

**Comment by Prabhatkumarsandvik** [comment] 2023-07-27 18:31
Hello Daniel,

Thanks for detailed explanation.

I will give you background regarding Veeam implementation. We are planning to configure Veeam backup for more than 30 servers. Curranty we are using TSM(Tivoli storage manager) and we are trying to replace TSM with Veeam.

 We take two types of backup on TAPE via TSM. One is file-level backup and another is database(TDP). TDP is using Archival style of TXN for incremental backup. Only recently modified document is backed-up.

 Regarding directory links actual database is stored in another drive and a Domino link is created inside Domino data directory.

Please suggest.

Thanks , Prabhat

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Daniel-Nashed** [comment] 2023-07-27 18:44
I think I explained most of it.
You can't use a different disk in case of snapshot.
What size are the disks? why do you need separate disks?
Usually you have one NSF disk and move everything else to different disks (NIFNSF, FT, DAOS, TRANSLOG)

You did not explain why you need archive translog. If this is for reducing the size of backup, that's not needed with snapshots any more.

If you want point in time recovery you need to find a way to backup the archive style translogs. this could be for example S3 or copy to a different disk and from where you back it up. 

Translog can be quite some size. And if you don't need point in time recovery outside the snapshot times or just for a couple of days, I would only use linear translog in combination with snapshot backups via Veeam.

**Comment by Daniel-Nashed** [comment] 2023-10-17 14:23
Can you describe where you directory link is? Directory links are not supported for snapshots. You can only have one disk in snapshot and there directory links make not much sense. the integration for the restore is using a script. the script does not have any logic to find databases based on directory links. I don't see that with a snapshot directory links make much sense, when only one disk is supported for snapshots.

**Comment by Prabhatkumarsandvik** [comment] 2023-10-17 16:13
Hello Daniel,

Our Domino data directory are stored in another drive and database is stored in another drive.
We use to create directory link like below so that we can utilize both drives.
***@***.***

We have many servers where application database is stored outside Domino data directory and we are not able to restore these database.

I have attached error.

Kindly suggest.

Thanks , prabhat


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by Daniel-Nashed** [comment] 2023-10-17 16:36
Only one disk is supported for snapshot backup. 
You should actually get an error during backup already depending on you configure multiple disks.
It checks during backup if the database is on the same volume then the data directory.

Because you are not explaining how exactly your directory structure looks like, I can not tell you why you are not getting an error here.

If more than one disk is involved in the NSF storage, you are running and unsupported configuration. this is part of the documented limitations of the snapshot backup. 

The background for this limitation is that with multiple disks it is almost impossible to build a standardized interface to backup and restore data.

If this is one disk and you are just outside the data directory with Notes links only the restore script would need some customization.
But because this is a complex, none standard scenario for the Veeam backup integration, this is outside anything the backup project can do for you.

You are outside the supported configuration and you are not providing even sufficient details.

- If this should be just one disk, there is no need for directory links and you could resolve it moving the data into the data directory
- If you have more than one disk with NSF data it's unsupported and I can't help you go get it working

If you are having details in your message, they are not showing up. It looks like you are replying to the issue response by mail and that's not showing up. 

Please log into GitHub and reply with details I can read.
Thanks
Daniel

**Comment by Prabhatkumarsandvik** [comment] 2023-10-17 18:05
I replied via email and my information was never complete. I am extremely sorry.
Paste recent email 
Hello Daniel,

Our Domino data directory is stored in another drive and the database is stored in another drive.
We used to create a directory link like below so that we could utilize both drives.
 
[backup error dir link.txt](https://github.com/HCL-TECH-SOFTWARE/domino-backup/files/12937804/backup.error.dir.link.txt)
[backup error.txt](https://github.com/HCL-TECH-SOFTWARE/domino-backup/files/12937805/backup.error.txt)

We have many servers where the application database is stored outside the Domino data directory and we are not able to restore these databases.
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/136735294/05021ed1-f2d6-4d57-ae70-349c86607441)

**Comment by Daniel-Nashed** [comment] 2023-10-17 19:43
can you share the content of the directory links? 
- I just want to understand where you store your data.
- is the main data directory below the binary directory?
- how big are you disks each?
- did you move out NIF via NIFNSF?
- did you move out FT index to different disks? 
- are those both significant size?
- are you using DAOS? where is DAOS located?
- where is translog located?

I can't help you with getting around with multiple directory links. if you want to use Veeam you can only have one volume for NSF. 

you only want to snapshot the data directory with the NSF data. I think with the right features enabled you can and should optimize your Domino data structure. This does not impact the application layer above, which does not see those directory links.

also directory links can effect performance. you can get away with 2-3 but with more directory links there can be issues as well.
I would avoid directory links in general and they are usually an indicator of a different problem.

We can try to help you to move to a supported setup, which also optimizes your snapshots.
You don't want NIF and FT nor DAOS in the same snapshot. The snapshot should contain the data directory on a separate drive.

Example setup:

- d:\binary directory
- **e:\notesdata**
- f:\ft
- g:\nif
- t:\translog
- h:\daos

If would usually at least split notesdata and daos. 
The other parts can be on one volume.

What you want to snapshot for Domino data backup is disk d:\

You can combine different parts on one volume. But **notesdata** is what you snapshot and what needs to be separated.
If you use DAOS, it should be a separate snapshot.

Using snapshots for backup changes the way you have to look into your infrastructure. 
This type of change would make your life easier in future also for other reasons.
I am not saying you need separate disks for everything. but everything should be moved out of the data directory and disk.

**Comment by Prabhatkumarsandvik** [comment] 2023-10-18 10:55
Hello Daniel,

Thank for your email and assistance. We have already configured Veeam on all servers now working to remove TSM.

Backup on servers are working fine and even we are able to restore database. But restore of database is not working if database is stored outside Domino binary.

I have reproduced this one of our test server for your suggestion but we are having many servers where data in TB are stored outside domino data directory.

Our domino directory is in D:\Lotus\Domino\data and program directory is in C:\Lotus\Domino.

We created a directory link and physically stored databases outside Domino directory(D:\Lotus\Domino\data). There is a link and we can open database outside directory from admin client.

Please check
***@***.***

***@***.***

These database are showing on backup database
[image]

But store is giving error
Searching for backup tag after mounting [dominobackup_20230914101942.tag]

-----------------------------------------------------------Search Results-----------------------------------------------------
TARGET            : D:\Lotus\Domino\Data\restore\restore1\testveem.nsf.DAD
FOUND_FILE_PATH   : []
FOUND_NOTESDATA   : []
-------------------------------------------------------------Search End-------------------------------------------------------


----------------------------------------

All required logs are attached and it contains scripts which we are using.


  *   I just want to understand where you store your data:-  All Domino data is stored under D lotus domino data. And we are trying to restore database from C drive
  *   is the main data directory below the binary directory? No , its in C drive and Data drive is in D
  *   how big are you disks each?:- Production servers are having 40Gbs databases
  *   did you move out NIF via NIFNSF?:- No
  *   did you move out FT index to different disks?:- No
  *   are those both significant size?:- On some servers
  *   are you using DAOS? where is DAOS located?:- No
  *   where is translog located?:- Its in E drive. Circular style .
HCL Case# CS0426621

Kindly suggest.

Thanks & Regards,
Prabhat Kumar
Technical Services Professional- Sandvik
Mobile: +919901113603 | E-mail: ***@***.******@***.***>
***@***.***



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Daniel-Nashed** [comment] 2023-10-18 11:16
not sure why you are starting again with the same thread. please read my last reply. 
there is no other supported way. Snapshots and classical backup like IBM Spectrum Protect are completely different approaches to backup Domino. You can't expect a 1:1 transition. You need to adopt to the nature of snapshot backup and apply today's best practices.

There is nothing more I can do for you in context of this issue. I am closing the issue.
There is no bug nor enhancement that can be added from the project side. 

Please re-read my last detailed response.

**Closed by Daniel-Nashed** 2023-10-18 11:16 UTC
Labels: help wanted
